### ISSUE TITLE
Build retention reliability issues

### ISSUE THREAD

**Issue by tkapin** [dotnet/arcade-services#2680]
Build retention does seem to be unreliable.

As reported on the [July servicing chat](https://teams.microsoft.com/l/message/19:586e1f66b0ca4584851d1d2124f6ab26@thread.v2/1686943724989?context=%7B%22contextType%22%3A%22chat%22%7D), the build 6.2.4.1 of [NuGet.Client-Official](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=8117&_a=summary) was successful and we inserted into SDK 6.0.3xx successfully (BAR 173078), but the build was deleted later on.

The goal of this issue / initiative is to:
1) Figure out why this build has not been retained
2) Propose a way to track and measure reliability of the build retention
3) Improve the build retention automation
4) Ensure that we have the full audit trail of the build retention in place

/cc @andriipatsula

**Comment by MilenaHristova** [comment]
checked the staging pipeline run for July servicing: https://dev.azure.com/dnceng/internal/_build/results?buildId=2208226&view=results
there is no build from NuGet.Client in the `manifest.json` and the build retention stage takes the builds from the manifest
will check previous runs to see if it was getting retained

**Comment by MilenaHristova** [comment]
from the `gather-drop` command of https://dev.azure.com/dnceng/internal/_build/results?buildId=2208354&view=logs&j=40e1e683-ea82-5be9-b25e-899b65e1c0cb&t=6e491791-6ce2-572a-3132-c49a3995e637

build 6.2.4.1 is found in the graph of dependencies of installer

`Done computing contributing builds`
  `Build - 20230622.30 of https://dev.azure.com/dnceng/internal/_git/dotnet-installer @ 2282fe998c54635c744653971f1903f98a33d49b`
  ..
  `Build - 6.2.4.1 of https://dev.azure.com/devdiv/DevDiv/_git/NuGet-NuGet.Client-Trusted @ 8fef55f5a55a3b4f2c96cd1a9b5ddc51d4b927f8`

but it's not downloaded:
`Skipping download of released build 6.2.4.1 of https://dev.azure.com/devdiv/DevDiv/_git/NuGet-NuGet.Client-Trusted @ 8fef55f5a55a3b4f2c96cd1a9b5ddc51d4b927f8`

**Comment by MilenaHristova** [comment]
@andriipatsula and I agreed that it's worth writing the build retention script in C# because

- logging can be improved by taking repository and pipeline names from the manifest instead of only bar and build ids and saving that information into objects so that it's easier to identify which build was causing the error
- transient errors can be avoided using the AzdoHttpHelper class
- monitoring of failures in the stage can be implemented - as notifications for failures and/or telemetry
- calls to the AzDO Api are already implemented (https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=/src/Microsoft.DotNet.Release/Microsoft.DotNet.ReleaseLib/Helpers/AzdoHttpHelper.cs&_a=contents&version=GBmain) including retries
- deserialization and operations with the manifest.json file are implemented https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=/src/Microsoft.DotNet.Release/Microsoft.DotNet.ReleaseLib/Helpers/IBuildManifestOperations.cs&_a=contents&version=GBmain

**Comment by tkapin** [comment]
Thanks for the detailed justification, the points look reasonable. Please make sure the new implementation is well covered by unit tests so we have a good example for other cases like that. Also, please think of how's this change going to be deployed and how are we going to measure the impact of the change.

**Comment by MilenaHristova** [comment]
I documented the failures in the step in https://github.com/dotnet/arcade-services/issues/2800

PR for the C# command: https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/32987

**Comment by MilenaHristova** [comment]
PR is merged and waiting for the next staging run to be fully validated

**Comment by MilenaHristova** [comment]
This is done and verified with the staging pipeline [run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2260602&view=logs&j=6606dbf2-e954-58ee-2b33-bc1713636658&t=b0dc1811-2829-5ba4-8fea-b6611d873001)
