### ISSUE TITLE
Use ReleaseCli operation for repo tagging in release pipeline

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade-services#3023]
Investigate using [create-release-tags operation](https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=/src/Microsoft.DotNet.Release/Microsoft.DotNet.ReleaseCli/src/Operations/CreateReleaseTagsOperation.cs) in the release pipeline instead of the [repo-tagging script](https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=/src/scripts/repo-tagging/repo-tagging.ps1)

## Linked issues:
- [ ] https://github.com/dotnet/arcade-services/issues/3008
- [ ] https://github.com/dotnet/arcade-services/issues/2455

**Comment by andriipatsula** [comment]
Please try to utilize the functionality from the arcade-services and replace LibGit2Sharp with "other" option. For reference https://github.com/dotnet/arcade-services/pull/2834

It 'd be nice to use a command (a proper C# tooling covered with tests) rather than a PowerShell script.
You mention, the [create-release-tags operation](https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=/src/Microsoft.DotNet.Release/Microsoft.DotNet.ReleaseCli/src/Operations/CreateReleaseTagsOperation.cs) command is slow - let's try the solution we introduce for VMR in the arcade-services repo.

**Comment by andriipatsula** [comment]
Try to shallow clone [CreateReleaseTagsOperation.cs](https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=/src/Microsoft.DotNet.Release/Microsoft.DotNet.ReleaseCli/src/Operations/CreateReleaseTagsOperation.cs&version=GBmain&line=95&lineEnd=102&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents)

**Comment by andriipatsula** [comment]
Linking: https://github.com/dotnet/arcade-services/issues/2455

**Comment by andriipatsula** [comment]
Linking: https://github.com/dotnet/arcade-services/issues/3008
