### ISSUE TITLE
Add Source Package Mappings to nuget.config

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#4017]
Since we use multiple feeds to restore our nuget packages, we have to suppress a warning NU1507 so our builds don't break.
If we added Source Package Mappings like in https://github.com/dotnet/arcade/pull/15110, we'd be able to remove the warning suppression, and our repo would be safer.

**Comment by richlander** [comment]
> repo would be safer.

Just so we're on the same page. PSM has its highest value where you mix feeds you control w/those you do not. We control all of our feeds. However, it still adds productivity value since it makes it more obvious which packages are coming from which feeds and makes transitive packages a lot more visible.
